### ISSUE TITLE
Please document RECAPTCHA_TESTING in the README

### ISSUE THREAD

**Issue by guettli** [torchbox/django-recaptcha#288]
**Is your feature request related to a problem? Please describe.**

I see that there is an environment variable `RECAPTCHA_TESTING` which gets used by captcha/fields.py

It would be nice to have this documented in the README.

My goal is to find a solution to unittest forms which use `ReCaptchaField`.

Related: https://github.com/torchbox/django-recaptcha/issues/218

**Comment by ckrybus** [comment]
It seems there was in the past a `RECAPTCHA_TESTING` env variable, but it is long gone. It was removed on 8th January 2019 in 586a280f9b92f2a3ea415f2818e430b1f68942e5.

To the maintainers: should it be reintroduced? If not, in my opinion this PR should be reversed, because it is just confusing.

I have the same problem as described in the linked tickets, there needs to be a way to deactivate recaptcha in tests. For now I will mock it as a workaround.

**Comment by Andrew-Chen-Wang** [comment]
please open a PR that I can merge; if I open one, I'd have to wait for another maintainer to approve

**Comment by jnns** [comment]
Thanks for the quick reply and the explanation. I will prepare a new merge request.
